[project]
name = "flywheel_util"
version = "0.0.1"
authors = [
  { name="Bryce Morrow", email="bryce@pif.vc" },
]
description = "Utilities for flywheel related software development"
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"